use_frameworks!

target 'MyFirstLib_Example' do
  pod 'MyFirstLib', :path => '../'

  target 'MyFirstLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
